# Generated by Django 5.2.8 on 2025-12-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('bodeguero', 'Bodeguero'), ('invitado', 'Invitado')], default='invitado', max_length=15),
        ),
    ]
